#pragma once

namespace strings
{

enum MiscStringId
{
	LoadingInterface = 1,
	LoadingStuff,
	LoadingObjects,
	LoadingUnits,
	LoadingItems,
	LoadingInfos,
	
	SavingMap = 10,
	SavingColormap,
	SavingHeightmap,
	SavingGrassmap,
	SavingObjects,
	SavingUnits,
	SavingItems,
	SavingInfos,
	SavingStates,
	SavingScripts,
	SavingDone,
	LoadingMap,
	LoadingColormap,
	LoadingHeightmap,
	LoadingGrassmap,
	LoadingMapObjects,
	LoadingMapUnits,
	LoadingMapItems,
	LoadingMapInfos,
	LoadingStates,
	LoadingScripts,
	LoadingEnvironment,
	LoadingDone,
	NumericSeparator,
	
	CompassN = 40,
	CompassE,
	CompassS,
	CompassW
};

enum MenuStringId
{
	Yes = 1,
	No,
	Cancel,
	Accept,
	Okay,
	ClickToChange,
	ClickToUse,
	Equal,
	Bigger,
	Smaller,
	EqualsBigger,
	EqualsSmaller,
	Unequal,
	PressAnyToContinue,
	Close,
	ColorSelection,
	Brighten,
	Shade,
	InvertColor,
	Path,
	LevelUp,
	HardsAndDrives,
	ToTheLeft,
	ToTheRight,
	Filename,
	File,
	NoFileSelected,
	MapSelection,
	Up,
	Down,
	NoMaps,
	NoMultiplayerMaps,
	Map,
	Created,
	At,
	/* Unknown */
	Line = 37,
	Column,
	XsIsland,
	Adventure,
	RandomIsland,
	SingleIsland,
	Multiplayer,
	Options,
	Editor,
	Credits,
	Quit,
	QuitX,
	Controls,
	Graphics,
	Sound,
	Action,
	Key,
	Forward,
	Backward,
	Left,
	Right,
	JumpCloseMenu,
	Sleep,
	Attack1,
	Attack2,
	NextWeapon,
	PreviousWeapon,
	Throwaway,
	Use,
	Chat,
	CharacterMenu,
	Rucksack,
	Diary,
	QuickLoad,
	QuickSave,
	Mouse,
	Sensibility,
	Invert,
	Smoothing,
	Resolution,
	ColorDepth,
	ViewRange,
	VerySmallViewRange,
	SmallViewRange,
	MediumViewRange,
	FarViewRange,
	VeryFarViewRange,
	LandscapeDetails,
	VeryLowDetails,
	LowDetails,
	MediumDetails,
	HighDetails,
	VeryHighDetails,
	WaterDetails,
	Minimal,
	Maximal,
	SkyDetails,
	EffectDetails,
	Grass,
	None,
	Few,
	Medium,
	Much,
	VeryMuch,
	Stuff,
	Postprocessing,
	LightEffects,
	WindWiggle,
	Fog,
	HardwareMultitexturing,
	MotionBlur,
	Intensity,
	/* 109 */
	SoundSlider = 110,
	Music,
	Off,
	SoundEffects,
	PlayerName,
	ServerPort,
	/* 116,
	117,
	118,
	119 */
	RestartNeeded = 120,
	HasToBeRestarted,
	ClickQuit,
	RestartAfterwards,
	/* Unknown = 124 */
	Online,
	Lan,
	CreateGame,
	Name,
	Player,
	Ping,
	Back,
	Join,
	ServerName,
	NoMapSelected,
	SelectMap,
	ServerPassword,
	PlayerLimit,
	PressKey,
	/* 139 */
	YouAreDead = 140,
	Character,
	Rucksack2,
	Diary2,
	Load,
	Save,
	Energy,
	Hunger,
	Thirst,
	Fatigue,
	XOutOfYFree,
	Use2,
	Combine,
	Discard,
	LoadGame,
	SaveGame,
	NoSavegames,
	Savegame,
	From,
	Build,
	YouDontKnowBuilding,
	BuildX,
	Chat2,
	Time,
	Sleep2,
	Exchange1,
	Exchange5,
	ExchangeAll,
	Air,
	Map2,
	Location,
	UpdateCommandList,
	UsedX,
	BuildingFinished,
	YouHaveNoMaterials,
	BuildingSiteReady,
	CannotBuidHere,
	BuildX2,
	Dig,
	Fish,
	FoundX,
	NoSpace,
	NewDiaryEntry,
	OnlyBuildOnLand,
	OnlyBuildOnWater,
	OnlyBuildOnBeach,
	OnlyBuildOnMountain,
	OnlyBuildOnShallowWater,
	TakeInHand,
	DeleteSavegame,
	DoYouWantDeleteX,
	QuitCurrentGame,
	CrackLock,
	OnlyBuildOnSpecial,
	EatOrDrink,
	CannotEatThis,
	CannotUseThis,
	PutXOnKeyY,
	AssignmentRemoved,
	CombineTo,
	NotPossibleYet,
	Exchange,
	ExchangeWithX,
	SellXXX,
	BuyXXX
};

enum EditorStringId
{
	// New map,
	// Load map,
	// Save map,
	// Map settings,
	// Quit editor,
	// Terrain,
	// Objects,
	// Units,
	// Items,
	// Infos,
	// Edit Heightmap,
	// Edit Colormap,
	// Edit Grassmap,
	// Raise Complete Terrain,
	// Lower Complete Terrain,
	// Round Off Terrain,
	// Distort Terrain,
	// Set Objects On Terrain,
	// Raise Terrain Border,
	// Lower Terrain Border,
	// Straighten Terrain Border,
	// Brush: mouse left/right/wheel to change the size,
	// Brush,
	// Change Height,
	// Straighten Terrain,
	// Round Off Terrain,
	// Distort Terrain,
	// Random Rotation,
	// Create Info at Camera,
	// Size,
	// Small,
	// Medium,
	// Big,
	// Terrain,
	// Normal,
	// Hills,
	// Mountains,
	// Desert,
	// Snow,
	// Swamp,
	// Vegetation,
	// None,
	// Normal,
	// Palms,
	// Deciduous Trees ,
	// Fir Trees ,
	// Wasteland,
	// Plants & Stones,
	// Animals,
	// Misc.,
	// Infos,
	// Map Time (Day:Hour:Min),
	// Freeze,
	// Skybox,
	// Beginning of a Skybox in the 'skies'-Dir,
	// Load Skybox,
	// Multiplayer Map,
	// Climate,
	// Normal (Sun/Rain),
	// Arctiv (Sun/Snow),
	// Sun Only,
	// Rain Only,
	// Snow Only,
	// Thunder Only,
	// Ambient SFX,
	// wav/mp3-file in 'sfx'-dir,
	// Load Ambient SFX,
	// Fog,
	// Fog Active Everytime,
	// Globale Script,
	// Script Editor,
	// Test Map,
	// More Options,
	// Map Informations,
	// Select File,
	// Fog Color,
	// Terrain Size,
	// Texture Size,
	// ($1 stored),
	// States,
	// Scripts,
	// Sum,
	// ($1 Models),
	// Adapt Energies To Definitionen,
	// Adapt Energies To Definitionen?,
	// Energies of $1 object(s) and $2 unit(s) adapted!,
	// All energies are already adapted!,
	// Changes energies of objects and units depending on the definitions,
	// Delete all objects,
	// Delete all objects of the type '$1'?,
	// Delete stored objects too?,
	// $1 object(s) of the type '$2' deleted!,
	// There are no objects of '$1'!,
	// Deletes all objects/units/items/infos of the type you selected on the left,
	// Delete children,
	// Delete States?,
	// Delete Scripts?,
	// Delete stored Items?,
	// $1 state(s), $2 script(s) and $3 stored item(s) deleted!,
	// Deletes states, scripts and stored items,
	// Nothing has been deleted,
	// Quit Map Editor?,
	// Attention: Everything you didnt save will get lost!,
	// Mapname,
	// Password,
	// Error While Loading Map,
	// Attention: Map already exists! Overwrite?,
	// Error While Saving Map,
	// Height Scaling For Import,
	// Import Heightmap,
	// Export Heightmap,
	// Current Height,
	// Alpha,
	// Brush,
	// Spray Can,
	// Brighten,
	// Shade,
	// Zoom,
	// Im-/Export Error!,
	// Colormap Size In Pixels,
	// Scale,
	// Import Colormap,
	// Export Colormap,
	// current color,
	// Color A,
	// Color B,
	// Color C,
	// Update Colormap With Heightmap,
	// Mode,
	// Set Grass,
	// Delete Grass,
	// Update Grassmap With Heightmap,
	// Object Properties,
	// Unit Properties,
	// Item Properties,
	// Info Properties,
	// ID,
	// Type,
	// Rotation,
	// Energy,
	// Delete,
	// stored,
	// Number,
	// Info,
	// Starting Position For Player,
	// Trigger,
	// Player,
	// Object(s),
	// Unit(s),
	// Item(s),
	// State,
	// Radius,
	// Aktive,
	// Instant Active,
	// All X Seconds,
	// All X Game Minutes,
	// At Certain Gametime,
	// Daily At Certain Time,
	// While Sleeping,
	// Seconds,
	// Game Minutes,
	// Day,
	// Hour,
	// Minute,
	// Object,
	// Unit,
	// Info,
	// Item,
	// No Special Properties,
	// Script,
	// Global Script,
	// Object Script ($1),
	// Unit Script ($1),
	// Item Script ($1),
	// Info Script ($1),
	// Delete Script?,
	// Import Script,
	// Export Script,
	// Add Command,
	// States,
	// leftclick: delete / rightclick: properties,
	// Add State,
	// forward,
	// back,
	// Add Item,
	// Addition,
	// Add Addition,
	// Free Addition,
	// The file has to be in a sub-dir of the mod,
	// Look,
	// Scripts in this info will NOT be executed,
	// State Properties,
	// Strenght/Damage,
	// Color,
	// Size/Range,
	// Alpha,
	// $1: [DEL] delete, [Space] free positioning,
	// $1: [DEL] delete,
	// Point Brushmode,
	// Line Brushmode,
	// List,
	// Goto Object,
	// Create,
	// testing - press [F12] to return to the editor,
	// Writing checkmap failed!,
	// Save before testing?,
	// Image Path,
	// Glow,
	// Fix,
	// Fix Vertically,
	// Signal,
	// Attract,
	// Distract,
	// All X days,
	// Number Part/Max.,
	// Fill Map Randomly,
	// Hide Menu,
	// Show Menu,
	// Attach To Object,
	// Soundpath,
	// (0=play everywhere),
	// Online Command Help For X,
	// Definition Variables,
	// Pipette,
	// All,
	// Set-Script
};

} // namespace strings
